info:
  app:
    name: trade-order-gateway-liubingxin
    env: local
    ver: v0.0.1

server:
  port: 8088

actions: http://campus.query1.ksyun.com:8089,http://campus.query2.ksyun.com:8089
meta: http://campus.meta.ksyun.com:8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_trade?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 3
    minimum-idle: 2
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    db: 3


#info:
#  app:
#    name: trade-order-gateway
#    env: local
#    ver: v0.0.1
#
#server:
#  port: 8088
#
#
#actions: http://campus.query1.ksyun.com:8089,http://campus.query2.ksyun.com:8089
#meta: http://campus.meta.ksyun.com:8090
#
#spring:
#  datasource:
#    url: jdbc:mysql://campus-dev.mysql.ksyun.com:63265/test_trade?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    maximum-pool-size: 3
#    minimum-idle: 2
#    username: test
#    password: test123
#  redis:
#    host: campus-dev.redis.ksyun.com
#    port: 26356
#    password: TkSbRi%xQtFkEX98BQR3yQ==
#    db: 3
